spring:
  application:
    name: aquarius

  modulith:
    events:
      completion-mode: delete

  jpa:
    open-in-view: false

springdoc:
  api-docs:
    enabled: false

aquarius:
  iam:
    captcha:
      password-login:
        store: redis
    bootstrap:
      admin:
        enabled: false
