spring:
  application:
    name: aquarius

  modulith:
    events:
      completion-mode: delete

springdoc:
  api-docs:
    enabled: false

aquarius:
  iam:
    bootstrap:
      admin:
        enabled: false
